export const route = {
    ONBOARDING: "ONBOARDING",
    SIGNIN: "SIGNIN",
    FORGET_PASSWORD_ONE: "FORGET_PASSWORD_ONE",
    FORGET_PASSWORD_TWO: "FORGET_PASSWORD_TWO",
    FORGET_PASSWORD_THREE: "FORGET_PASSWORD_THREE",
    RESET_PASSWORD: "RESET_PASSWORD",
    VERIFY_EMAIL: "VERIFY_EMAIL",
    SIGNUP: "SIGNUP",
    REGISTER_ONE: "REGISTER_ONE",
    REGISTER_VERIFY: "REGISTER_VERIFY",
    REGISTER_INTEREST: "REGISTER_INTEREST",
    
    BOTTOM_TAB: "BOTTOM_TAB",
    
    // Drawer
    DASHBOARD: "DASHBOARD",

    // bottom 
    MAIN_HOME: "MAIN_HOME",
    HOME: "HOME",
    SETTING: "SETTING",
    
}

const ROUTE = route;

export default ROUTE;