export const route = {
    ONBOARDING: "ONBOARDING",
    SIGNIN: "SIGNIN",
    FORGET_PASSWORD_ONE: "FORGET_PASSWORD_ONE",
    FORGET_PASSWORD_TWO: "FORGET_PASSWORD_TWO",
    FORGET_PASSWORD_THREE: "FORGET_PASSWORD_THREE",
    RESET_PASSWORD: "RESET_PASSWORD",
    VERIFY_EMAIL: "VERIFY_EMAIL",
    SIGNUP: "SIGNUP",
    REGISTER_ONE: "REGISTER_ONE",
    REGISTER_VERIFY: "REGISTER_VERIFY",
    REGISTER_INTEREST: "REGISTER_INTEREST",
    
    BOTTOM_TAB: "BOTTOM_TAB",
    
    // Drawer
    DASHBOARD: "DASHBOARD",
    
    REFER_FRIEND: "REFER_FRIEND",
    PROXY_BID: "PROXY_BID",
    REGULAR_BID: "REGULAR_BID",
    BIDDING_CLOSED: "BIDDING_CLOSED",
    ITEM_INVOICE: "ITEM_INVOICE",

    // bottom 
    MAIN_HOME: "MAIN_HOME",
    THUNDER: "THUNDER",
    CONTRACT: "CONTRACT",
    PROFILE: "PROFILE",

    ITEM_SUCCESS: "ITEM_SUCCESS",
    BID_WON: "BID_WON",
    RATE_BID: "RATE_BID",
    CATEGORY_SCREEN: "CATEGORY_SCREEN",
    HISTORIC_BID: "HISTORIC_BID",
    SECURITY: "SECURITY",
    MY_ACCOUNT_VIEW: "MY_ACCOUNT_VIEW",
    MY_ACCOUNT_EDIT: "MY_ACCOUNT_EDIT",
    ADDRESS_BOOK: "ADDRESS_BOOK",
    ADDRESS_BOOK_EDIT: "ADDRESS_BOOK_EDIT",
    ADDRESS_BOOK_EDIT_DATA: "ADDRESS_BOOK_EDIT_DATA",
    CARD_INFO: "CARD_INFO",
    NOTIFICATION_SETTING: "NOTIFICATION_SETTING",
    NOTIFICATION_CONTENT: "NOTIFICATION_CONTENT",
    FAQ_SCREEN: "FAQ_SCREEN",
}

const ROUTE = route;

export default ROUTE;