const ACTION_TYPE = {
    APP_LOADER: "APP::LOADER",
    APP_LOADER_COVER: "APP::LOADER::COVER",
    LOGGED_IN: "LOGGED::IN",
    ACTION_LOGINSETTER: "ACTION::LOGINSETTER",
    ACTION_LOGOUTSETTER: "ACTION::LOGOUTSETTER",
    AUTH_POPUP: "AUTH::POPUP",
    WALLET: "APP:USER:WALLET",
    MY_ADDRESSES: "APP:USER:MY_ADDRESSES",
    FCM_TOKEN: "APP:SETTING:FCM_TOKEN",
    MY_CARDS: "APP:USER:MY_CARDS",
    BIDS: "APP:SYSTEM:BIDS",
    AUCTION: "APP:SYSTEM:AUCTION",
    CATEGORY: "APP:SYSTEM:CATEGORY",
    CURRENT_BID: "APP:USER:CURRENT_BID",
    ACTIVE_BID: "APP:USER:ACTIVE_BID",
    WON_BID: "APP:USER:WON_BID",
    PAST_BID: "APP:USER:PAST_BID",
    NOTIFICATION: "APP:USER:NOTIFICATION",
    NOTIFICATION_PREFERENCE: "APP:USER:NOTIFICATION_PREFERENCE",
    APP_NAVIGATION: "APP:SYSTEM:APP_NAVIGATION",
    DEEP_LINK: "APP:SYSTEM:DEEP_LINK"
}

export default ACTION_TYPE;